### ISSUE TITLE
Rename yoeo.names.yaml

### ISSUE THREAD

**Issue by phinik** [bit-bots/YOEO#93]
The file yoeo.names.yaml is called yoeo_names.yaml in [bitbots_vision](https://github.com/bit-bots/bitbots_vision/tree/70d788b630fe8ff3218f97453466e9f1dd33d51f). We should make the naming scheme consistent.

**Comment by jaagut** [comment]
Also our defaults seem to be broken: https://github.com/bit-bots/YOEO/blob/eac3bc689be601a4c912bccfeda2fee2716bc1c1/config/custom.data#L4

**Comment by phinik** [comment]
> Also our defaults seem to be broken:
> 
> https://github.com/bit-bots/YOEO/blob/eac3bc689be601a4c912bccfeda2fee2716bc1c1/config/custom.data#L4

fixed with https://github.com/bit-bots/YOEO/pull/94
